<h1><center>Dynamic Mode Decomposition Varients</center></h1>

In [2]:
import numpy as np

In [3]:
data = np.array([[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8],[1,2,3,4,5,6,7,8]])
data

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [4]:
S1 = data[:,0:data.shape[1]-1]
S1

array([[1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7],
       [1, 2, 3, 4, 5, 6, 7]])

In [5]:
S2 = data[:,1:data.shape[1]]
S2

array([[2, 3, 4, 5, 6, 7, 8],
       [2, 3, 4, 5, 6, 7, 8],
       [2, 3, 4, 5, 6, 7, 8],
       [2, 3, 4, 5, 6, 7, 8],
       [2, 3, 4, 5, 6, 7, 8],
       [2, 3, 4, 5, 6, 7, 8],
       [2, 3, 4, 5, 6, 7, 8],
       [2, 3, 4, 5, 6, 7, 8],
       [2, 3, 4, 5, 6, 7, 8],
       [2, 3, 4, 5, 6, 7, 8],
       [2, 3, 4, 5, 6, 7, 8],
       [2, 3, 4, 5, 6, 7, 8],
       [2, 3, 4, 5, 6, 7, 8],
       [2, 3, 4, 5, 6, 7, 8]])

<h2>Original Form</h2>

In [12]:
def my_dmd(X, Y, truncate=None):   
    U2,Sig2,Vh2 = np.linalg.svd(X, False) # SVD of input matrix  
    if truncate is None:
        r = len(Sig2)
    else:
        truncate
    U = U2[:,:r]
    Sig = np.diag(Sig2)[:r,:r]
    V = Vh2.conj().T[:,:r]
    Atil = np.dot(np.dot(np.dot(U.conj().T, Y), V), np.linalg.inv(Sig)) # build A tilde
    mu,W = np.linalg.eig(Atil)
    Phi = np.dot(np.dot(np.dot(Y, V), np.linalg.inv(Sig)), W) # build DMD modes
    return mu, Phi

In [56]:
[eig_val1, eig_vec1] = my_dmd(S1, S2, truncate=None)

In [57]:
eig_val1

array([ 1.20000000e+00,  1.38461379e+81, -9.34691418e+63,  3.12151521e+48,
       -3.88672878e+47,  1.85737035e+33, -3.88991164e+32])

In [58]:
eig_vec1

array([[-3.20713490e-01,  5.85415774e+70, -2.44725311e+53,
        -1.85766628e+38,  3.03926603e+38, -2.07138759e+34,
         2.22796876e+34],
       [-3.20713490e-01,  5.85415774e+70, -2.44725311e+53,
        -1.85766628e+38,  3.03926603e+38, -2.07138759e+34,
         2.22796876e+34],
       [-3.20713490e-01,  5.85415774e+70, -2.44725311e+53,
        -1.85766628e+38,  3.03926603e+38, -2.07138759e+34,
         2.22796876e+34],
       [-3.20713490e-01,  5.85415774e+70, -2.44725311e+53,
        -1.85766628e+38,  3.03926603e+38, -2.07138759e+34,
         2.22796876e+34],
       [-3.20713490e-01,  5.85415774e+70, -2.44725311e+53,
        -1.85766628e+38,  3.03926603e+38, -2.07138759e+34,
         2.22796876e+34],
       [-3.20713490e-01,  5.85415774e+70, -2.44725311e+53,
        -1.85766628e+38,  3.03926603e+38, -2.07138759e+34,
         2.22796876e+34],
       [-3.20713490e-01,  5.85415774e+70, -2.44725311e+53,
        -1.85766628e+38,  3.03926603e+38, -2.07138759e+34,
         2.2279687

<h2>Total DMD</h2>

In [15]:
def get_derived_matrices(X, Y, truncate=None):  
    T = np.concatenate((X,Y),axis=0)
    U2,Sig2,Vh2 = np.linalg.svd(T, False) # SVD of input matrix  
    if truncate is None:
        r = len(Sig2)
    else:
        truncate
    U = U2[:,:r]
    Sig = np.diag(Sig2)[:r,:r]
    V = Vh2.conj().T[:,:r]
    E1 = np.dot(S1,V)
    E2 = np.dot(S2,V)
    return E1, E2

In [21]:
#[E1, E2] = get_derived_matrices(S1, S2, truncate=None)
def T_DMD(S1, S2, truncate=None):
    [X, Y] = get_derived_matrices(S1,S2, truncate=None)
    U2,Sig2,Vh2 = np.linalg.svd(X, False) # SVD of input matrix  
    if truncate is None:
        r = len(Sig2)
    else:
        truncate
    U = U2[:,:r]
    Sig = np.diag(Sig2)[:r,:r]
    V = Vh2.conj().T[:,:r]
    Atil = np.dot(np.dot(np.dot(U.conj().T, Y), V), np.linalg.pinv(Sig)) # build A tilde
    mu,W = np.linalg.eig(Atil)
    Phi = np.dot(np.dot(np.dot(Y, V), np.linalg.pinv(Sig)), W) # build DMD modes
    return mu, Phi

In [59]:
[eig_val2, eig_vec2] = T_DMD(S1, S2, truncate=None)

In [60]:
eig_val2

array([0. , 0. , 0. , 0. , 0. , 0. , 1.2])

In [61]:
eig_vec2

array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.32071349],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.32071349],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.32071349],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.32071349],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.32071349],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.32071349],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.32071349],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.32071349],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        , -0.32071349],
       [ 0.        ,  0.    

<h2>Randomized DMD</h2>

In [62]:
def rsvd(A, Omega):
    Y = A @ Omega
    Q, _ = np.linalg.qr(Y)
    B = Q.T @ A
    u_tilde, s, v = np.linalg.svd(B, full_matrices = 0)
    u = Q @ u_tilde
    return u, s, v

In [67]:
def Rsvd_dmd(X, Y, truncate=None):
    #rank = np.linalg.matrix_rank(X)
    #print(rank)
    rank = 7
    Omega = np.random.randn(X.shape[1], rank)
    U2,Sig2,Vh2 = rsvd(X, Omega) # SVD of input matrix  
    if truncate is None:
        r = len(Sig2)
    else:
        truncate
    U = U2[:,:r]
    Sig = np.diag(Sig2)[:r,:r]
    V = Vh2.conj().T[:,:r]
    Atil = np.dot(np.dot(np.dot(U.conj().T, Y), V), np.linalg.inv(Sig)) # build A tilde
    mu,W = np.linalg.eig(Atil)
    Phi = np.dot(np.dot(np.dot(Y, V), np.linalg.inv(Sig)), W) # build DMD modes
    return mu, Phi

In [68]:
[eig_val3, eig_vec3] = Rsvd_dmd(S1, S2, truncate=None)

In [69]:
eig_val3

array([-3.75736480e+15+4.93653109e+15j, -3.75736480e+15-4.93653109e+15j,
        7.39639862e+13+0.00000000e+00j, -1.89648610e+01+0.00000000e+00j,
       -2.84730669e-01+0.00000000e+00j,  2.21515480e-01+0.00000000e+00j,
        2.40744071e-02+0.00000000e+00j])

In [70]:
eig_vec3

array([[ 1.00419804e+15-1.31934335e+15j,  1.00419804e+15+1.31934335e+15j,
        -1.97677058e+13+0.00000000e+00j, -5.11503834e+00+0.00000000e+00j,
        -1.22563671e-01+0.00000000e+00j,  1.27362789e-02+0.00000000e+00j,
        -4.00320719e-02+0.00000000e+00j],
       [ 1.00419804e+15-1.31934335e+15j,  1.00419804e+15+1.31934335e+15j,
        -1.97677058e+13+0.00000000e+00j, -5.11503834e+00+0.00000000e+00j,
        -1.22563671e-01+0.00000000e+00j,  1.27362789e-02+0.00000000e+00j,
        -4.00320719e-02+0.00000000e+00j],
       [ 1.00419804e+15-1.31934335e+15j,  1.00419804e+15+1.31934335e+15j,
        -1.97677058e+13+0.00000000e+00j, -5.11503834e+00+0.00000000e+00j,
        -1.22563671e-01+0.00000000e+00j,  1.27362789e-02+0.00000000e+00j,
        -4.00320719e-02+0.00000000e+00j],
       [ 1.00419804e+15-1.31934335e+15j,  1.00419804e+15+1.31934335e+15j,
        -1.97677058e+13+0.00000000e+00j, -5.11503834e+00+0.00000000e+00j,
        -1.22563671e-01+0.00000000e+00j,  1.27362789e-02+0.0